Java Dockerfile

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /java-app

COPY Hello.java .

RUN javac Hello.java

CMD ["java", "Hello"]

Python 

FROM python:3.10-slim

WORKDIR /python-app

COPY app.py .

CMD ["python3", "app.py"]

HTML

FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

React 

FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

Maven Dockerfile

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/hello-java-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]


Flask

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]



